### PR TITLE
Guidelines for Guideline creation/approval

### PR DESCRIPTION
**Pull request by d4weed**
As discussed in the decisions team, it would be useful to have some rules of thumb to help people create new guidelines and make sure we are all consistent.

This is work in progress, active participation is encouraged

Proposed text:

### What is a guideline?

A guideline is a written statement that helps make autonomous decisions.

### Where can I find guidelines?

All guidelines are stored in this repository. You can find them either by using keyword search or navigating the categories.

### What if I cannot find a guideline?

You need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a consent process to create a guideline based on the advice.

### What if the guideline exists but it is not sufficient?

Sometimes you may discover that an existing guideline does not cover your specific case, is out of sync with current best practice or contradicts other guidelines. In such case you don't have to follow it, but you need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a consent process to amend the guideline.

### When not to create guidelines?

It's important to reflect on your motivation for proposing a new guideline. The goal with guidance is to have only that which is necessary to make the company run smoothly and well. It should not be in reaction to bad behaviour or one-off situation. Assess whether feedback or conflict resolution might be a more appropriate means of dealing with it.

### How are guidelines created / amended?

Guideline creation and amendment is done through **consent process** (to-do: add a link to consent process here), as a result of the advice process. The person/s who propose the guideline creation / amendment are responsible for moving the process forward. Team-led guideline creation is encouraged. Even if a guideline has a scope (company, office, functional team, project team) the whole team can participate in the consent process.

### How to write a good guideline?

- For new guidelines, make sure the guideline you are adding doesn't already exist.
- For existing ones, make sure you review the history of changes to see if the issue you propose to amend has already been discussed before.
- Perform due diligence to understand context and background around the issue (has this been discussed before, is there a *de facto* practice already in place, are there conflicting views about the matter?)
- Whenever possible try to keep the current high-level structure. Create new sections or subsections only when necessary.
- Keep things as simple as possible, only write new guidelines when they are needed.
- Write in clear, specific and actionable terms. Guidelines are decision helpers, not judgments or theoretical statements.

### To create or amend a guideline you can start a [Pull Request](https://help.github.com/articles/using-pull-requests). Keep in mind:

- Start your PR with a short and meaningful title (e.g. "Guideline for hiring process").
- Briefly explain the motivation for the guideline creation/amendment and the context and background.
- The created / amended text of the guideline should also be added to the PR text for easier reading.
- Add as assignees the people who are leading this guideline creation, including yourself.
- Add as reviewers the people who should be involved by giving advice, or who are directly affected. Remember that anyone can participate.
- Announce the new guideline creation / amendment process on #general channel in Slack.
- Allow up to 3 days for comments.
- Announce the outcome on #general channel in Slack.

### When participating in a Guideline discussion process:

- Please follow the Consent process. In that process a decision does not require everybody to agree, it only requires that nobody raises a meaningful objection.
- Use the reactions :+1: "Agree", :confused: "Disagree", :-1: "Object" and explain clearly afterward your reasons.
- Use the keyword "Proposed changes" to suggest amendments, corrections or additions.
- If you want to propose a bigger change, edit the file directly and include a link to the diff in the comment box. You can also paste the new wording in the comment box.
- If you were assigned as a [reviewer of a pull request](https://help.github.com/articles/about-pull-request-reviews/), you have additional tools available to comment on particular sections of the text, approve or request changes. 
- Try not to make judgments. Base your opinions on facts or rational reasons rather than judgments or emotions.
- Use [Non-Violent Communication](https://vizzuality.github.io/playbook/conflict-resolution/)
- Provide your comments in a timely manner, normally up to 3 days.

### Using GitHub Pages

This is where you can access the content of this repository as a web page: https://vizzuality.github.io/playbook/

You can use the [editor on GitHub](https://github.com/Vizzuality/playbook/edit/master/README.md) to maintain and preview the content for your website in Markdown files.

Whenever you commit to this repository, GitHub Pages will run [Jekyll](https://jekyllrb.com/) to rebuild the pages in your site, from the content in your Markdown files.

### CODE REVIEW

**Comment by d4weed** [comment]
Perhaps a meaningful code for agree/ disagree / object could be

image -> agree
image -> disagree
image -> object

given than in this context (consent) disagreement is weaker than objection

What do you think?

**Comment by agnessa** [comment]
I'd use something stronger for object / block and perhaps we could also add "abstain"? E.g.
👍 agree
😑 abstain
👎 disagree
⛔️ object

**Comment by d4weed** [comment]
Sounds good to me @agnessa 

Do you think we should make amendments to the text directly in the first post, or in a comment below?

**Comment by agnessa** [comment]
I amended the text directly, because it's easier to see the changes side by side this way. If it's no good, easy to revert the commit as well.

**Comment by agnessa** [comment]
So this is how the text reads now after my changes:

## Welcome to Vizzuality's Guidelines

### What is a guideline?

A guideline is a written statement that helps make autonomous decisions.

### Where can I find guidelines?

All guidelines are stored in this repository. You can find them either by using keyword search or navigating the categories.

### What if I cannot find a guideline?

You need to follow the *advice process* to arrive at a decision. Anyone in the advice process can initiate a process to create a guideline based on the advice.

### What if the guideline exists but I don't want to follow it?

You need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a process to amend the guideline based on the advice.

### How are guidelines created / amended?

Guideline creation and amendment is done through **consent process** (to-do: add a link to consent process here), as a result of the advice process. The person/s who propose the guideline creation / amendment are responsible for moving the process forward. Team-led guideline creation is encouraged. Even if a guideline has a scope (company, office, functional team, project team) the whole team can participate in the consent process.

### How to write a good guideline?

- For new guidelines, make sure the guideline you are adding doesn't already exist.
- For existing ones, make sure you review the history of changes to see if the issue you propose to amend has already been discussed before.
- Perform due diligence to understand context and background around the issue (has this been discussed before, is there a *de facto* practice already in place, are there conflicting views about the matter?)
- Whenever possible try to keep the current high-level structure. Create new sections or subsections only when necessary.
- Keep things as simple as possible, only write new guidelines when they are needed.
- Write in clear, specific and actionable terms. Guidelines are decision helpers, not judgments or theoretical statements.

### To create or amend a guideline you can start a [Pull Request](https://help.github.com/articles/using-pull-requests). Keep in mind:

- Start your PR with a short and meaningful title (e.g. "Guideline for hiring process")
- Explain in a couple paragraphs the motivation for the guideline creation/amendment and the context and background
- The created/amended text of the guideline should also be added to the PR text for easier reading.

TBD:
- Add as assignees the team of people who are leading this guideline creation, including yourself (a team can be formed at this step too)
- Add as reviewers the people you think should be involved by giving advice, or because they are directly affected TBD: should we create teams according to scopes?). Remember, though that anyone can participate
- Announce the new guideline creation/amendment process on Slack (TBD: where?)

### When participating in a Guideline discussion process:

- Please follow the Consent process
- Use the keywords "Agree", "Disagree", "Object" explaining clearly afterward the reasons
- Use the keyword "Proposed changes" to suggest amendments, corrections or additions
- Try not to make judgments, base your opinions on facts or rational reasons rather than judgments or emotions
- Use Non-Violent Communication (to-do: link to NVC guidelines here)

You can use the [editor on GitHub](https://github.com/Vizzuality/playbook/edit/master/README.md) to maintain and preview the content for your website in Markdown files.

Whenever you commit to this repository, GitHub Pages will run [Jekyll](https://jekyllrb.com/) to rebuild the pages in your site, from the content in your Markdown files.

### Markdown

Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for

```markdown
Syntax highlighted code block

# Header 1
## Header 2
### Header 3

- Bulleted
- List

1. Numbered
2. List

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)
```

For more details see [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/).

### Jekyll Themes

Your Pages site will use the layout and styles from the Jekyll theme you have selected in your [repository settings](https://github.com/Vizzuality/playbook/settings). The name of this theme is saved in the Jekyll `_config.yml` configuration file.

### Support or Contact

Having trouble with Pages? Check out our [documentation](https://help.github.com/categories/github-pages-basics/) or [contact support](https://github.com/contact) and we’ll help you sort it out.

**Comment by agnessa** [comment]
I think we need to work on the TBD points. I'd rather not leave them in, because it gives the impression of "under construction, not applicable yet". What we should aim for is for a first draft, but internally consistent and complete, the idea being anyone can challenge it if not fit for purpose.

**Comment by agnessa** [comment]
One thing that we should probably add to the PR instructions is how to "propose changes to the proposed change". We say "The created/amended text of the guideline should also be added to the PR text for easier reading.", but when others later want to incorporate amendments, how do they do it? Two main options here I guess, as was demonstrated even in this current PR:
- Add the changed section of text into a comment
- Make the changes on the files directly
I think both have advantages and flaws. The first one "reads better", but will be a nightmare to manage when multiple people suggest alterations and with small changes it is not easy to spot what actually changed. The second one is less easy to follow, because the new version does not show up in the comment thread, but can be easily diffed with previous version, which to me is the benefit of using a version control system to manage this. We could potentially also do both - make the change in the file + paste the new version of the file in a comment. Whichever way, we should specify this in instructions.

**Comment by d4weed** [comment]
I think in the long run people will get used to changing the file itself, but initially, it may be helpful to still ad the changes in the comment

**Comment by d4weed** [comment]
Also, about TBDs, it's just about deciding how to use "assignees" and "reviewers" and the slack channel to use. For nowwe could just use general.

We can also add an integration so PRs pop up there automatically, but that may be a bit annoying

**Comment by agnessa** [comment]
The interesting feature that reviewers have at their disposal is the "approve" / "request changes" and I agree with how you propose to use reviewers / assignees. What I'm not sure of is whether it's worth taking the time to create teams, because there doesn't seem to be a way to use teams for quick assignment (or is there and I haven't found it?). I also agree about using general.

**Comment by agnessa** [comment]
do you think it's worth adding issue / pull request templates? https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by agnessa** [comment]
Current full text, after incorporating comment on when not to create guidelines.

## Welcome to Vizzuality's Guidelines

### What is a guideline?

A guideline is a written statement that helps make autonomous decisions.

### Where can I find guidelines?

All guidelines are stored in this repository. You can find them either by using keyword search or navigating the categories.

### What if I cannot find a guideline?

You need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a process to create a guideline based on the advice.

### What if the guideline exists but I don't want to follow it?

You need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a process to amend the guideline based on the advice.

### When not to create guidelines?

It's important to reflect on your motivation for proposing a new guideline. The goal with guidance is to have only that which is necessary to make the company run smoothly and well. It should not be in reaction to bad behaviour or one-off situation. Assess whether feedback or conflict resolution might be a more appropriate means of dealing with it.

### How are guidelines created / amended?

Guideline creation and amendment is done through **consent process** (to-do: add a link to consent process here), as a result of the advice process. The person/s who propose the guideline creation / amendment are responsible for moving the process forward. Team-led guideline creation is encouraged. Even if a guideline has a scope (company, office, functional team, project team) the whole team can participate in the consent process.

### How to write a good guideline?

- For new guidelines, make sure the guideline you are adding doesn't already exist.
- For existing ones, make sure you review the history of changes to see if the issue you propose to amend has already been discussed before.
- Perform due diligence to understand context and background around the issue (has this been discussed before, is there a *de facto* practice already in place, are there conflicting views about the matter?)
- Whenever possible try to keep the current high-level structure. Create new sections or subsections only when necessary.
- Keep things as simple as possible, only write new guidelines when they are needed.
- Write in clear, specific and actionable terms. Guidelines are decision helpers, not judgments or theoretical statements.

### To create or amend a guideline you can start a [Pull Request](https://help.github.com/articles/using-pull-requests). Keep in mind:

- Start your PR with a short and meaningful title (e.g. "Guideline for hiring process").
- Briefly explain the motivation for the guideline creation/amendment and the context and background.
- The created / amended text of the guideline should also be added to the PR text for easier reading.
- Add as assignees the people who are leading this guideline creation, including yourself.
- Add as reviewers the people who should be involved by giving advice, or who are directly affected. Remember, though, that anyone can participate.
- Announce the new guideline creation / amendment process on #general channel in Slack.

### When participating in a Guideline discussion process:

- Please follow the Consent process. In that process a decision does not require everybody to agree, it only requires that nobody raises a meaningful objection.
- Use the reactions :+1: "Agree", :confused: "Disagree", :-1: "Object" and explain clearly afterward your reasons.
- Use the keyword "Proposed changes" to suggest amendments, corrections or additions.
- If you want to propose a bigger change, edit the file directly and include a link to the diff in the comment box. You can also paste the new wording in the comment box.
- Try not to make judgments, base your opinions on facts or rational reasons rather than judgments or emotions.
- Use Non-Violent Communication (to-do: link to NVC guidelines here).

### Using GitHub Pages

This is where you can access the content of this repository as a web page: https://vizzuality.github.io/playbook/

You can use the [editor on GitHub](https://github.com/Vizzuality/playbook/edit/master/README.md) to maintain and preview the content for your website in Markdown files.

Whenever you commit to this repository, GitHub Pages will run [Jekyll](https://jekyllrb.com/) to rebuild the pages in your site, from the content in your Markdown files.

### Markdown

Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for

```markdown
Syntax highlighted code block

# Header 1
## Header 2
### Header 3

- Bulleted
- List

1. Numbered
2. List

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)
```

For more details see [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/).

### Jekyll Themes

Your Pages site will use the layout and styles from the Jekyll theme you have selected in your [repository settings](https://github.com/Vizzuality/playbook/settings). The name of this theme is saved in the Jekyll `_config.yml` configuration file.

### Support or Contact

Having trouble with Pages? Check out our [documentation](https://help.github.com/categories/github-pages-basics/) or [contact support](https://github.com/contact) and we’ll help you sort it out.

**Comment by simaob** [comment]
Great job putting this together. It all reads well and sounds sensible and clear. I have only one comment on the section: **What if the guideline exists but I don't want to follow it?**

I wonder if it's worth clarifying here that "not wanting" to follow a guideline is not the right attitude. You might not agree with the existing guideline and hence start a process to amend it, but given that you need to follow the advice process, not wanting is not a valid reason. I guess it's implicit, but I'd suggest make it more explicit.

/end of comment

Thanks for everyone's work on this! =)

**Comment by agnessa** [comment]
Thanks @simaob! Current full text:

## Welcome to Vizzuality's Guidelines

### What is a guideline?

A guideline is a written statement that helps make autonomous decisions.

### Where can I find guidelines?

All guidelines are stored in this repository. You can find them either by using keyword search or navigating the categories.

### What if I cannot find a guideline?

You need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a consent process to create a guideline based on the advice.

### What if the guideline exists but it is not sufficient?

Sometimes you may discover that an existing guideline does not cover your specific case, is out of sync with current best practice or contradicts other guidelines. In such case you don't have to follow it, but you need to follow the **advice process** to arrive at a decision. Anyone in the advice process can initiate a consent process to amend the guideline.

### When not to create guidelines?

It's important to reflect on your motivation for proposing a new guideline. The goal with guidance is to have only that which is necessary to make the company run smoothly and well. It should not be in reaction to bad behaviour or one-off situation. Assess whether feedback or conflict resolution might be a more appropriate means of dealing with it.

### How are guidelines created / amended?

Guideline creation and amendment is done through **consent process** (to-do: add a link to consent process here), as a result of the advice process. The person/s who propose the guideline creation / amendment are responsible for moving the process forward. Team-led guideline creation is encouraged. Even if a guideline has a scope (company, office, functional team, project team) the whole team can participate in the consent process.

### How to write a good guideline?

- For new guidelines, make sure the guideline you are adding doesn't already exist.
- For existing ones, make sure you review the history of changes to see if the issue you propose to amend has already been discussed before.
- Perform due diligence to understand context and background around the issue (has this been discussed before, is there a *de facto* practice already in place, are there conflicting views about the matter?)
- Whenever possible try to keep the current high-level structure. Create new sections or subsections only when necessary.
- Keep things as simple as possible, only write new guidelines when they are needed.
- Write in clear, specific and actionable terms. Guidelines are decision helpers, not judgments or theoretical statements.

### To create or amend a guideline you can start a [Pull Request](https://help.github.com/articles/using-pull-requests). Keep in mind:

- Start your PR with a short and meaningful title (e.g. "Guideline for hiring process").
- Briefly explain the motivation for the guideline creation/amendment and the context and background.
- The created / amended text of the guideline should also be added to the PR text for easier reading.
- Add as assignees the people who are leading this guideline creation, including yourself.
- Add as reviewers the people who should be involved by giving advice, or who are directly affected. Remember, though, that anyone can participate.
- Announce the new guideline creation / amendment process on #general channel in Slack.
- Allow up to 3 days for comments.
- Announce the outcome on #general channel in Slack.

### When participating in a Guideline discussion process:

- Please follow the Consent process. In that process a decision does not require everybody to agree, it only requires that nobody raises a meaningful objection.
- Use the reactions :+1: "Agree", :confused: "Disagree", :-1: "Object" and explain clearly afterward your reasons.
- Use the keyword "Proposed changes" to suggest amendments, corrections or additions.
- If you want to propose a bigger change, edit the file directly and include a link to the diff in the comment box. You can also paste the new wording in the comment box.
- Try not to make judgments, base your opinions on facts or rational reasons rather than judgments or emotions.
- Use Non-Violent Communication (to-do: link to NVC guidelines here).
- Provide your comments in a timely manner, normally up to 3 days.

### Using GitHub Pages

This is where you can access the content of this repository as a web page: https://vizzuality.github.io/playbook/

You can use the [editor on GitHub](https://github.com/Vizzuality/playbook/edit/master/README.md) to maintain and preview the content for your website in Markdown files.

Whenever you commit to this repository, GitHub Pages will run [Jekyll](https://jekyllrb.com/) to rebuild the pages in your site, from the content in your Markdown files.

### Markdown

Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for

```markdown
Syntax highlighted code block

# Header 1
## Header 2
### Header 3

- Bulleted
- List

1. Numbered
2. List

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)
```

For more details see [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/).

### Jekyll Themes

Your Pages site will use the layout and styles from the Jekyll theme you have selected in your [repository settings](https://github.com/Vizzuality/playbook/settings). The name of this theme is saved in the Jekyll `_config.yml` configuration file.

### Support or Contact

Having trouble with Pages? Check out our [documentation](https://help.github.com/categories/github-pages-basics/) or [contact support](https://github.com/contact) and we’ll help you sort it out.

**Comment by Jamie-Gibson** [comment]
I'd just like to say that I followed this guidance yesterday when I was adding the Vizz Ethos and conflict resolution documents and it was very easy to follow and clear. I mean obviously the easy bit was already decided (do we need a guideline on this), but it helped me decide (at least in my own mind) that we do need an additional guidance specifically for the mediation process. We don't need a specific guidance on conflict resolution a) because we have a guideline on client satisfaction (forthcoming from Craig in the Vizz Way) and b) we have the general guidance on NVC.

**Comment by agnessa** [comment]
I have also been de-facto following this, so time to merge. We probably might need more consideration around the use of "reviewers" vs . "assignees", but I guess it's easier to raise a PR with a specific change than to keep working on guidelines without a meta-guideline.

**Pull request merged**
