### PR TITLE
How to allocate cloud resources

### PR DESCRIPTION
**Pull request by tiagojsag**

### CODE REVIEW

**Comment by simaob** [comment]
Very nice write up, Tiago. Maybe it would be worth adding some words for the cases where we set it all up and pay from our pocket and then we need to charge the client. What do you think? Tks!

**Comment by tiagojsag** [comment]
@simaob I though about that, but decided to avoid going into the "not recommended" scenarios, because there are a few of them, and because I want us to focus on pushing for the recommended approach, instead of saying "this alternative is also ok" when we actually don't want to use alternatives. We can be flexible and adapt to client's needs as we go (and maybe this is what I should write here) but those situations should be the exceptions, not the acceptable plan B we're sort of ok with.

**Comment by hotzevzl** [comment]
Thanks Tiago: very clear and comprehensive while short enough to be useful.

A section about how to handle access may be out of scope here, and it would partly overlap with the existing security guideline, but maybe worth thinking about this, even if it ends up being a separate small guideline (or an update to the security guideline), perhaps?

I am thinking about things such as individual accounts for our team, for the client and any freelancers, common pitfalls regarding service account keys, API keys, account invalidations, key rotations, what to do when cloud services only allow to have one user account per service (we were talking about per-project email forwards to the whole internal project team in the WI channel recently for other reasons, but they could be useful in these cases too)... this kind of stuff.

**Comment by sorodrigo** [comment]
Thanks for this, really useful! Given our recent copernicus odyssey to decide whether we can use or we can't use Carto. I'd like to have a couple of lines detailing what are the necessary steps to decide if we can or we can't use some paid resources, specially focusing on the in-house projects.

**Comment by tiagojsag** [comment]
@hotzevzl I added a line advising readers to keep security best practices in mind, as I agree they are very important (which is why I am the author of said security guidelines guideline :P )

As for the challenges to do with credential handling, I also added a few lines on those. I didn't go into full details, like covering freelancers, rotation and such, as I want to keep this simple and practical.

**Comment by tiagojsag** [comment]
@sorodrigo added a line saying you should ask the PM

**Pull request merged**
