### PR TITLE
update purpose description

### PR DESCRIPTION
**Pull request by 01painadam**
Updates Vizz's purpose to 2020 version as per webpage.

### CODE REVIEW

**Comment by 01painadam** [comment]
@d4weed Is it worth having an internal and external facing (simplified) purpose?

I'll also remove the xmas quiz part 😄

**Comment by d4weed** [comment]
Jokes apart, I think that when we added the "short" purpose statement to the site we talked about having two versions, the short one, and a longer one that was something like:

Our purpose is the creation of a better future for our planet and society.

> We aim to reach a fair and sustainable planet by creating tools that radically empower people to make positive changes now.
> 
> But looks like we didn't stop to update anything here at the end.

I don't think it's bad to have different statements for different purposes, as long as they are coherent

**Comment by d4weed** [comment]
oops, just merged haha

**Comment by 01painadam** [comment]
No worries! I'll add both as a single statement.

**Pull request merged**
