### PR TITLE
Document 2FA is now required on github accounts

### PR DESCRIPTION
**Pull request by tiagojsag**
Since this is pretty minor, I'd say merge in a week (28/03/2019) unless someone is against it

### CODE REVIEW

**Comment by simaob** [comment]
I'd suggest adding this link to the text: https://help.github.com/en/articles/configuring-two-factor-authentication

**Comment by tiagojsag** [comment]
I suggest you make a commit with it :P

**Comment by simaob** [comment]
Flow goes that if someone makes suggestions they have to be accepted first, otherwise this would be chaos. YOU FAILED THE FLOW!! AH AH AH! But if you agree it's useful, I can add it of course. =) or any of us could've done it already in the time we spent writing these beautiful comments. Joke's on us, I guess.

**Comment by tiagojsag** [comment]
I'm not in the flow? but but but... 

image

And yeah, I'm just going to keep writing stuff and stuff and stuff. not your request. no. that would be productive time. and that's not what we do.

**Pull request merged**
