### PR TITLE
Feedback Loops Proposal

### PR DESCRIPTION
**Pull request by 01painadam**
# Feedback Loops at Vizzuality *UPDATED*
 
## *Overview*

The idea here is to lay out a set of principles that should be universally applied when giving and taking feedback, regardless of the context that feedback is being given or received, and should be used as a guideline for both participants in the process.

***

## Nurturing a Culture

The goals are:

- Everyone is comfortable and open.
- We address challenges together.
- We have clear expectations.
- There are no stupid questions.
- There are ongoing positive and/or corrective processes for everyone.
- We all make it a priority to improve each other and the whole organization. 

Every day, we should aim to improve ourselves, the company, and offer useful feedback to our peers.

***

# Giving Effective Feedback

### When to Give Feedback?

The first step is recognising opportunities to give feedback. 

- *During handovers*
  
  Handovers between functional groups are likely to surface opportunities for rich feedback. Bridging the gap in understanding between researchers, designers, data-scientists, and devs is core to becoming more productive and efficient so try go give feedback that can aid smooth these transitions.

- *When you see good work being done!*
  
  Positive feedback is essential to making sure we keep on doing what we're awesome at.

- *When you recognise an opportunity for improvement*
  
  More on this below.

- *At the end of a sprint*

  How could teh sprint have run more smoothly? Feedback between you and your PM could well improve productivity of future sprints.

***

## What to give Feedback about?

Try to choose talking points that are relevant to current work/projects, and ensure that your points aren’t all negative ones!

Feedback is most useful to someone when likelihood of improvement is high. So it is important to identify what areas are more appropriate to give feedback on - some are more difficult than others! Consider the following:

```
(easy)    Technical Skills
  
  Ʌ       Time Management
  |
  |       Knowledge
  |
  |       Attitudes
  |
  V       Habits
   
(hard)    Personality
```

Try to focus on easier topics and successes that are likely to get the biggest positive returns in a reasonable time frame.

***

## Giving Feedback Effectively

These principles are concerned with how to give feedback effectively:

1. **Feedback needs to be shared *frequently* and in *context*.**

    This is probably the most important set of principles to work under. There are two ways that ‘in context’ can be interpreted. Both are important!

    *Time-context*:

    You should aim to discuss recent topics. Trying to improve on something that happened two weeks ago will always be more difficult than when the event is fresh in the mind and can be acted upon immediately. Giving feedback little and often achieves this.

    *Topic-context*:

    Also, always aim to ensure that your discussion sticks to the point. Don’t go off on tangents and talk about unrelated issues. Find the core of what you want to discuss, reduce it down to only a few key points, and stick to them. Be clear and direct.

2. **Aim to achieve a specific outcome, needs to be realistic in its expectations.**
   
   Discuss next steps together, ensuring that the goals outlined are achievable within a reasonable time frame. Don’t be afraid to block goals into smaller chunks or waypoints. Larger, more abstract goals (“you should improve your cooking skills”) should be matched with smaller, clearer task that help the receiver of the feedback achieve the goal (“try using a recipe from this cooking book next time”). Making progress feel real and attainable goes a long way!

3. **Expresses a point of view rather than an absolute truth.**
   
   Remember that your feedback represents a point of view, one that he recipient may not necessarily agree with. Don’t back yourself into a corner by presenting your opinions as fact, and allow the recipient to respond.
   
   Criticism and praise should ultimately be viewed as being the same so being objective about your thoughts nurtures a two way conversation which is less about ‘*good and bad*’ and more about ‘*improvement and how to get there*’.

4. **It should show respect for the recipient and is a two-way conversation.**
   
   As has been outlined in the other three points, acting on feedback can break down when viewed as an order or directive by the recipient. Always nurture the idea of feedback as a collaboration. Respect their thoughts and be prepared to shift your stance at times.

***

### When to Give Feedback?

The first step is recognising opportunities to give feedback. 

- *During handovers*
  
  Handovers between functional groups are likely to surface opportunities for rich feedback. Bridging the gap in understanding between researchers, designers, data-scientists, and devs is core to becoming more productive and efficient so try go give feedback that can aid smooth these transitions.

- *When you see good work being done!*
  
  Positive feedback is essential to making sure we keep on doing what we're awesome at.

- *When you recognise an opportunity for improvement*
  
  More on this below.

- *At the end of a sprint*

  How could the sprint have run more smoothly? Feedback between you and your PM could well improve productivity of future sprints.

***

# Acting on Feedback

## When to request Feedback

If you feel like you haven't had any feedback in a while (*> 1 week*) then its on you to seek it.

*\<insert formal process\>*

***

## Receiving Feedback and Acting on it Effectively

Conversely, these principles are focused on how to act effectively during/after receiving feedback:

1. **Clarify**
   
   Summarise the plan, do you know where you are now and where you need to be to improve? Do you fully understand what is the downside of the current approach/behavior, its negative impact, and do you agree that it can be improved? If any points seems unresolved, be open to ask about them explicitly, or if appropriate, revise them. Be open to asking for help of other people, who may have dealt with and overcome similar situations in the past.

2. **Outlining Next Steps**
   
   As soon as possible afterwards, outline the steps you are going to take to act on the feedback given. If you prefer, discuss this during feedback. If there are multiple components, specify each one and how you will achieve each. Identify when and how follow-up will occur and be as specific as possible. Set a time frame for achieving the primary goal and, if appropriate, identify smaller goals along the way. Make some rough notes to help you remember!

3. **Following Up & Bridging the Gap**
   
   On the agreed schedule, meet with the person that gave you feedback and evaluate the progress so far. Check if you were able to meet your goals, and if not, work together on a revised strategy. Review any potential negative side-effects of your strategy, and adapt your plan if needed. If it’s the case, review your next steps and timeline, making sure all of them are clear and achievable.

4. **Self Assessing & Feeding Forward**
   
   Review how you improved. After a feedback the feedback process went, how it went, and monitor how follow-up is progressing. The learning process doesn’t finish when the feedback session closes, this principle is basic and has impact on your colleagues and direct reports, and everyone on the team benefits.

***

*See you, space cowboy!*

### CODE REVIEW

**Comment by Jamie-Gibson** [comment]
hey this looks good so far. some thoughts
- let's add more details into the "when to give feedback" - I think this might be one of the key bits that would help people actually start giving feedback
- In addition to that, should we add in a "ask for feedback?" idea - if you feel like you haven't received feedback on something in a while, it's up to you to find some reviewers
- add some 'next steps'? "we're looking into machine feedback to help with code etc", "we need to see how these guidelines + moving to a flatter organisation will change the review process", "we're recruiting feedback champions now to start this off, want to help?"

**Comment by 01painadam** [comment]
1) Agreed - could be a separate doc?

2) Yeah, I love this idea and hadn't considered it!

3) Yes, these can be added to the Roadmap

**Comment by 01painadam** [comment]
# Update Overview

- Separate Giving/Receiving Feedback overviews
- Flesh out when to give feedback section
- Add automated testing to roadmap
- Update roadmap

***

# Feedback Loops Roadmap

### Next Steps / Timeline

- Build concrete guidline doc
- Outline general rules for framing the system (frequency, who-who, how, central axioms)
- General framework for different interactions
- Champions/Ambassadors
- Scaffold behaviour (Phase 2)

***

### Open/Unanswered Questions

Things that need to be discussed moving forwards. See the [open-questions document](https://docs.google.com/document/d/1eGlzH5fOxIchVyLRipWBrNBIgdQ18-BHVmVD-PnEmoI/edit#heading=h.aqcfnjgggoxb) to keep up-to-date.

Areas/Contexts that have not been addressed:

1. Replacing/Augmenting Performance Reviews

    At this stage have addressed formative (ongoing) feedback, but we are lacking a solution to summative (end of line) feedback, mainly in the context of formal reviews.

2. Knowledge Sharing

    Teaching eachother. Not getting bogged down in problems that others have solved.

3. Retrospectives

    Creating guidlines for retrospectives. What have we learned? What can be done better? If we do this it also lends well to feedforward processes...

4. Feedforward

    How do we set ourselves up in kick-offs so that we work with more efficiency? Should we have a guideline for documenting the things learned?

5. Automated Feedback

    Using testing as a means of feedback for devs.

**Comment by Jamie-Gibson** [comment]
Only new comment to this is to check out the retrospective guidelines we have already https://vizzuality.github.io/playbook/projects/retrospective/ to help point 3

**Comment by 01painadam** [comment]
Nice, thanks Jamie! I'll add the link and outline the import stuff inside of point 3.

**Comment by tomasmoose** [comment]
@01painadam know its a small thing, but could we formulate this one a bit different? 

"**There are no stupid questions**" to "**There's no such thing as a stupid question**"  

the first one for me sounds more like "we don't want stupid questions" :)

**Comment by 01painadam** [comment]
Haha, poor phrasing - will update 👍

**Comment by craigmmills** [comment]
Proposed change: In the easy to hard feedback diagram,  "Time management" doesn't seems fit  with the other categories. It seems oddly specific. Perhaps it could be removed or changed to "working practices"

**Comment by 01painadam** [comment]
Good point, it was very specific. Maybe I can outline a general category and give an example for each. e.g. `Working Practices (e.g. Time Management)`

**Pull request merged**
