### PR TITLE
Strategic Priorities for rest of 2018

### PR DESCRIPTION
**Pull request by Jamie-Gibson**
In this PR we’re asking for your comments about the 2 Strategic Priorities for the rest of 2018 and the 7 priority activities to achieve them. 

## Strategic Priorities **UP FOR REVIEW UNTIL MONDAY 13TH**

We have two main priorities for the next six months.

1. Increase the urgency of our work and complete projects more quickly.
Under this priority we will undertake five main activities:
   * The 6 systems we’re creating are built around increasing speed and quality and are consentmentized and operational by the end of 2018.
   * Build an organistional structure that empowers individual ownership of our work, rewarding positive behaviour and a drive towards our results.
   * Build a strategy for better communication during meetings (including good practices and equipment).
   * Hire staff with different skills/ backgrounds who can create new tools, data, research and ideas.
   * Define internal training needs for our current staff to create new tools, data, research and ideas.

2. Win the largest, best, most impactful, and most profitable projects.
Under this priority, we will undertake four main activities:
    * Work on 20 projects in 2019 with an average sized income of 200k
    * Win more grants to build our research team
    * Extend our client base into Europe
    * Investigate ways to change budget, rates, scope management or types of project to ensure we're setting ourselves up for profitability

**This is in order to double our per staff profit, so we're able to invest that new profit in more initiatives that achieve our purpose.**

### CODE REVIEW

**Comment by chichibouse** [comment]
(gonna re-write my comments from #23 here as well): 
I like the purpose and vision statements; they are inspiring and well-phrased.
I was wondering about a couple of details regarding the strategy (these are not blocking comments btw, just clarifications perhaps)

1. In the strategy, the idea of doing things "more quickly" seem to be take precedence over the rest. Although I understand that there is a concern for productivity, I think there should be a stronger emphasis on "maintaining (or even improving) impact and quality." Overall, I am missing the link between the vision and the strategy: if what we aim for is impact, I am unsure whether working faster would necessarily lead to that.
2. The "train staff" part seems a bit unspecific: are we trying to foster soft skills? Technical skills? Both?

**Comment by d4weed** [comment]
> Invest in equipment that allows us to communicate faster between offices and clients

I don't think this should be a strategic priority in itself, but rather part of a strategy to have better communication. A good preparation and practices like speaking to the microphone, not overlapping in conversations, using methods to indicate you want to speak, moderating, muting when not speaking, and in general, establishing a culture that improves remote calls is as important (or even more) than the equipment.

I think the strategic priority should reflect this, and in terms of priority, I think the behavior change should take precedence.

**Comment by Jamie-Gibson** [comment]
Ok thanks for comments so far

@martindub Martin - yes good point, and camellia explains the impact point well. the training element has been refined to be more specific (i.e. define what skills we should build next year with a larger training budget)

@simaob yeah good point I'm going to add that. some of it is in priority 2, some in priority 1

@d4weed point taken. The reason tech was highest was because we've had a few very painful remote meetings recently (all-hands being one of them) where the technology (boom mics, auto-switching the network) could help much faster (acknowledging that cultural change takes time). i've reworded to be about a meeting strategy (of which tech may or may not be a big component)...

**Comment by sorodrigo** [comment]
IDK if people were actually reviewing the changes made afterwards, (I sure wasn't, thought description was up to date), so I updated the PR description to match the latest version.

**Pull request merged**
