### PR TITLE
Absences guideline

### PR DESCRIPTION
**Pull request by agnessa**
Extracted from #8, this guideline deals only with requesting and recording absences and limited availability.

# Absences

Everyone affected by your absence needs to be able to easily understand your and others' availability. This is done by using tools which allow to record and access this information in one place.

The company-wide tool for requesting absences is Bamboo. Aim to give as much notice for your absence as you reasonably can, as a rule of thumb: two weeks if you're away for less than two weeks, a month if longer.

Currently we don't have a company-wide standard of recording limited availability due to travel, participation in workshops or events. We would like to propose one company standard, and two additional extras if this fits within your workflow. 

## Company Standard: Bamboo "unavailable" option

We already record all vacation absences in Bamboo. The who's out Calendar in Bamboo also lets you see, across the whole team, when people have planned abscences. You can use the iCal feed to import this list into Google Calendar, if you like to see it there too. 

We'd also like to extend that to help us record other absences. If you are going to be working but mostly unavailable because you are travelling, in a client sprint or in a conference, please use the "unavailable" option in Bamboo to set those dates in advance. The process is the same as with time off requests.

image

image

Please note that the absences are not pulled through in the iCal feed: always use Bamboo as the primary source of who's in and who's out. 

## Optional extra: Teamweek

In some projects we use Teamweek to plan our work for weeks or months at a time. For these staff involved in planning, it can be useful that you also record your absences in Teamweek too. You can use the "holiday" or "maternal/parental leave" project. If your absence is related to a specific project workshop or meeting, add the words "unavailable" into the task description (+ allocate 8 hours a day to the task) so people can differentiate it from regular project work. For non-project absences not covered by the above, you can create a new project; again, make sure to label it as unavailable time. This is visible in the timeline in the same way as your project assignments.

image

If your team is not using Teamweek for the projects you're working on, please don't feel like you have to use this. 

## Optional Extra: Google Calendar Out of Office

Many of our clients use Calendar applications to arrange meetings or events. Using the Out of Office feature in Google Calendar can help improve the visibility of your absence to them when they arrange meetings.  

When you mark yourself as Out of Office using Google Calendar, whenever anyone is booking a meeting with you when you are out, they will get an automatic reply telling them you are on not available. Where colleagues or clients have access to view your calendar, they can automatically see that you are unavailable.

You can set this up by choosing the "out of office" option when creating a new event. Select the start/ end dates and write a decline message explaining when you will be back.

### CODE REVIEW

**Comment by CV-Gate** [comment]
I think that offering two options is very confusing. We should decide one of them.

**Comment by simaob** [comment]
I think each team or group of people might pick one or the other, but I don't think is a bad idea to share both as ideas.

**Comment by CV-Gate** [comment]
I think it is, I was saying on the other PR that I need to see it in one place. If we recommend both I'm not even knowing where this should happen.

**Comment by agnessa** [comment]
I guess to establish a new company-wide guideline we need more participation in the consent process.

**Comment by Jamie-Gibson** [comment]
I would argue that Teamweek is the place, for most transparency. Unless there's a setting we can open on Bamboo, I don't get the whole team overview. Especially if we're trying to promote cross-team collaboration, we can't have 2 guidelines, and we also need the thing that's most open. 

I'm going to propose a third option in a commit

**Comment by CV-Gate** [comment]
I think that's a good point Jamie, what worries me more is not taking decisions because we need more participation. I'd say, let's promote the participation. If still there is no much participation we should take decisions anyway.

**Comment by Jamie-Gibson** [comment]
New Suggestion: 

## Google Calendar Out of Office

You can mark yourself as Out of Office using Google Calendar. This means, whenever anyone is booking a meeting, they can automatically see that you are away. And when a client books a meeting with you, they will get an automatic reply telling them you are on vacation. 

You can set this up by choosing the "out of office" option when creating a new event. Select the start/ end dates and write a decline message explaining when you will be back. 

screen shot 2018-07-26 at 09 50 29

**Comment by CV-Gate** [comment]
I think that's quite useful Jamie but will we have the 'who is out' feature using Google Calendar?

**Comment by CV-Gate** [comment]
I don't think that looking at everyone's calendar is what I need, I think it's just the opposite, have a look to one place and know who is out. I like Bamboo for that because the 'who is out calendar' just works. If we don't have a common tool for this and we must use different tools or even new ways to get this info, I don't think it's a valid argument to say that someone doesn't use Bamboo daily, because we aren't using the calendar for that right now either.
As I'm seeing that there are some objections to use Bamboo I'd like to know the reasons for this apart of 'I am not using it' because there is nothing that all of us are using for this.

**Comment by tiagojsag** [comment]
I probably wasn't clear. My main need to know when someone is absent is when I need to schedule meetings. And I think we all use google calendar for that, so that's why I suggest we use the same tool for both things, as it makes things easier.

**Comment by Jamie-Gibson** [comment]
My only objection to Bamboo is that I don't know how I can see the absences and vacations of others. Maybe it's just a permissions thing that I can't see who's out? If that was something everyone can access then that's great...

My personal preference for Teamweek is because you can see the absences in the context of project deadlines/ project phasing. And I think you can quickly get a project/ team view of who's in/ who's out... But as I think we discussed in the other thread, if it's only some people using Teamweek for that kind of planning then that won't work...

My 2nd suggestion (non-blocking comment) about bamboo is around day-to-day meeting arrangement (and the only argument for google calendar). Quite often I'm arranging meetings (sprints etc) using Google Calendar. Especially as I float between many projects/ many teams, it's good to know the days/weeks that people are out so I can make sure they're included in meetings. My need is to see, very quickly, if a certain slot is good or not, without opening a big discussion in slack that distracts people from their work. If I can see absences directly in google calendar, that makes my life a lot easier than having to tab back and forth between bamboo and calendar. This isn't a blocker thought - I can have 2 screens open at the same time!

**Comment by tiagojsag** [comment]
I just found out bamboo offers calendar feeds which can be imported to google calendar. I don't know if they update automatically over time or not, but if they do, this could be a solution that would allow us to add stuff to bamboo only and see it show up automagically on GCal

**Comment by d4weed** [comment]
Sorry to be late to this conversation.

Bamboo does offer calendar feeds that sync to Google, so it's just a matter of adding a new calendar feed and it will sync with bamboo automatically (I have it on my calendar since we started using bamboo)

**Comment by Jamie-Gibson** [comment]
Ok so with this new knowledge about Bamboo's 'who's out' feature + the Google sync, I believe we should move forward with Bamboo as the company standard for recording absences. All others are optional (i.e. you can add Out of Office to you G calendar so clients get automatic rejections, and use Teamweek if your projects are using that for planning). 

Should we move this to a country-wide consent process next week after the all-hands?

**Comment by agnessa** [comment]
Do instructions on the google sync belong here? Or would that be in a separate guideline on using the calendar?
And do you mean to make it the company standard to record "unavailable" in bamboo - does that sync via the calendar feed as well?

**Comment by Jamie-Gibson** [comment]
Very funny, that's also something I can't do right now in Bamboo because of some weird settings issues... I wanted to try adding some unavailable time to see if it comes through into google.

**Pull request merged**
