### PR TITLE
Include current benefits

### PR DESCRIPTION
**Pull request by j8seangel**
This PR includes the list of the current benefits with the general and the specific ones by the different offices.

### CODE REVIEW

**Comment by agnessa** [comment]
Does the pension scheme belong here?

**Comment by d4weed** [comment]
> Does the pension scheme belong here?

I believe so, yeah. I think we had it in a doc somewhere, let me see if I can find it

**Comment by j8seangel** [comment]
After asking Laura seems that this is a rule to follow in the UK contracts. 
But as we are thinking on adding more than the law requires it could be considered as a benefit then.

**Comment by clementprdhomme** [comment]
Yes, this is a legal requirement for workers in the UK: https://www.gov.uk/workplace-pensions/joining-a-workplace-pension

**Pull request merged**
